# DO NOT DELETE: Beginning of Haskell dependencies
CodeBreaker.o : CodeBreaker.hs
CodeBreakerTests.o : CodeBreakerTests.hs
CodeBreakerTests.o : CodeBreaker.hi
# DO NOT DELETE: End of Haskell dependencies
